const data = {
    typeMatches: [
        {
            matchType: "International",
            seriesMatches: [
                {
                    seriesAdWrapper: {
                        seriesId: 8786,
                        seriesName: "India tour of England, 2025",
                        matches: [
                            {
                                matchInfo: {
                                    matchId: 105762,
                                    seriesId: 8786,
                                    seriesName: "India tour of England, 2025",
                                    matchDesc: "1st Test",
                                    matchFormat: "TEST",
                                    startDate: "1750413600000",
                                    endDate: "1750784400000",
                                    state: "Stumps",
                                    status: "Day 4: Stumps - England need 350 runs",
                                    team1: {
                                        teamId: 2,
                                        teamName: "India",
                                        teamSName: "IND",
                                        imageId: 719031,
                                    },
                                    team2: {
                                        teamId: 9,
                                        teamName: "England",
                                        teamSName: "ENG",
                                        imageId: 172123,
                                    },
                                    venueInfo: {
                                        id: 66,
                                        ground: "Headingley",
                                        city: "Leeds",
                                        timezone: "+01:00",
                                        latitude: "53.817622",
                                        longitude: "-1.58211",
                                    },
                                    currBatTeamId: 9,
                                    seriesStartDt: "1750377600000",
                                    seriesEndDt: "1754438400000",
                                    isTimeAnnounced: true,
                                    stateTitle: "Stumps",
                                },
                                matchScore: {
                                    team1Score: {
                                        inngs1: {
                                            inningsId: 1,
                                            runs: 471,
                                            wickets: 10,
                                            overs: 112.6,
                                        },
                                        inngs2: {
                                            inningsId: 3,
                                            runs: 364,
                                            wickets: 10,
                                            overs: 95.6,
                                        },
                                    },
                                    team2Score: {
                                        inngs1: {
                                            inningsId: 2,
                                            runs: 465,
                                            wickets: 10,
                                            overs: 100.4,
                                        },
                                        inngs2: {
                                            inningsId: 4,
                                            runs: 21,
                                            overs: 5.6,
                                        },
                                    },
                                },
                            },
                        ],
                    },
                },
            ],
        },
        {
            matchType: "League",
            seriesMatches: [
                {
                    seriesAdWrapper: {
                        seriesId: 9614,
                        seriesName: "Major League Cricket 2025",
                        matches: [
                            {
                                matchInfo: {
                                    matchId: 117161,
                                    seriesId: 9614,
                                    seriesName: "Major League Cricket 2025",
                                    matchDesc: "14th Match ",
                                    matchFormat: "T20",
                                    startDate: "1750723200000",
                                    endDate: "1750735800000",
                                    state: "Complete",
                                    status: "San Francisco Unicorns won by 47 runs",
                                    team1: {
                                        teamId: 1584,
                                        teamName: "San Francisco Unicorns",
                                        teamSName: "SFU",
                                        imageId: 333487,
                                    },
                                    team2: {
                                        teamId: 1573,
                                        teamName: "MI New York",
                                        teamSName: "MINY",
                                        imageId: 334729,
                                    },
                                    venueInfo: {
                                        id: 1668,
                                        ground: "Grand Prairie Stadium",
                                        city: "Dallas",
                                        timezone: "-05:00",
                                        latitude: "32.67942",
                                        longitude: "-97.028338",
                                    },
                                    currBatTeamId: 1584,
                                    seriesStartDt: "1749686400000",
                                    seriesEndDt: "1752537600000",
                                    isTimeAnnounced: true,
                                    stateTitle: "Complete",
                                    isFantasyEnabled: true,
                                },
                                matchScore: {
                                    team1Score: {
                                        inngs1: {
                                            inningsId: 1,
                                            runs: 246,
                                            wickets: 4,
                                            overs: 19.6,
                                        },
                                    },
                                    team2Score: {
                                        inngs1: {
                                            inningsId: 2,
                                            runs: 199,
                                            wickets: 6,
                                            overs: 19.6,
                                        },
                                    },
                                },
                            },
                        ],
                    },
                },
            ],
        },
        {
            matchType: "Domestic",
            seriesMatches: [
                {
                    seriesAdWrapper: {
                        seriesId: 9360,
                        seriesName: "County Championship Division One 2025",
                        matches: [
                            {
                                matchInfo: {
                                    matchId: 113058,
                                    seriesId: 9360,
                                    seriesName: "County Championship Division One 2025",
                                    matchDesc: "36th Match",
                                    matchFormat: "TEST",
                                    startDate: "1750586400000",
                                    endDate: "1750870800000",
                                    state: "Stumps",
                                    status: "Day 2: Stumps - Durham trail by 112 runs",
                                    team1: {
                                        teamId: 41,
                                        teamName: "Sussex",
                                        teamSName: "SUS",
                                        imageId: 172148,
                                    },
                                    team2: {
                                        teamId: 141,
                                        teamName: "Durham",
                                        teamSName: "DUR",
                                        imageId: 172208,
                                    },
                                    venueInfo: {
                                        id: 60,
                                        ground: "Riverside Ground",
                                        city: "Chester-le-Street",
                                        timezone: "+01:00",
                                        latitude: "54.849531",
                                        longitude: "-1.56103",
                                    },
                                    currBatTeamId: 141,
                                    seriesStartDt: "1743724800000",
                                    seriesEndDt: "1759104000000",
                                    isTimeAnnounced: true,
                                    stateTitle: "Stumps",
                                },
                                matchScore: {
                                    team1Score: {
                                        inngs1: {
                                            inningsId: 1,
                                            runs: 361,
                                            wickets: 10,
                                            overs: 106.5,
                                        },
                                    },
                                    team2Score: {
                                        inngs1: {
                                            inningsId: 2,
                                            runs: 249,
                                            wickets: 5,
                                            overs: 82.1,
                                        },
                                    },
                                },
                            },
                            {
                                matchInfo: {
                                    matchId: 113082,
                                    seriesId: 9360,
                                    seriesName: "County Championship Division One 2025",
                                    matchDesc: "39th Match",
                                    matchFormat: "TEST",
                                    startDate: "1750586400000",
                                    endDate: "1750870800000",
                                    state: "Stumps",
                                    status: "Day 2: Stumps - Worcestershire trail by 13 runs",
                                    team1: {
                                        teamId: 147,
                                        teamName: "Worcestershire",
                                        teamSName: "WORCS",
                                        imageId: 172214,
                                    },
                                    team2: {
                                        teamId: 148,
                                        teamName: "Surrey",
                                        teamSName: "SUR",
                                        imageId: 172215,
                                    },
                                    venueInfo: {
                                        id: 225,
                                        ground: "New Road",
                                        city: "Worcester",
                                        timezone: "+01:00",
                                        latitude: "52.189294",
                                        longitude: "-2.2268",
                                    },
                                    currBatTeamId: 147,
                                    seriesStartDt: "1743724800000",
                                    seriesEndDt: "1759104000000",
                                    isTimeAnnounced: true,
                                    stateTitle: "Stumps",
                                },
                                matchScore: {
                                    team1Score: {
                                        inngs1: {
                                            inningsId: 1,
                                            runs: 209,
                                            wickets: 10,
                                            overs: 78.5,
                                        },
                                        inngs2: {
                                            inningsId: 3,
                                            runs: 69,
                                            wickets: 4,
                                            overs: 16.6,
                                        },
                                    },
                                    team2Score: {
                                        inngs1: {
                                            inningsId: 2,
                                            runs: 291,
                                            wickets: 10,
                                            overs: 91.3,
                                        },
                                    },
                                },
                            },
                            {
                                matchInfo: {
                                    matchId: 113067,
                                    seriesId: 9360,
                                    seriesName: "County Championship Division One 2025",
                                    matchDesc: "37th Match",
                                    matchFormat: "TEST",
                                    startDate: "1750586400000",
                                    endDate: "1750870800000",
                                    state: "Stumps",
                                    status: "Day 2: Stumps - Hampshire trail by 3 runs",
                                    team1: {
                                        teamId: 152,
                                        teamName: "Essex",
                                        teamSName: "ESS",
                                        imageId: 172219,
                                    },
                                    team2: {
                                        teamId: 153,
                                        teamName: "Hampshire",
                                        teamSName: "HAM",
                                        imageId: 172220,
                                    },
                                    venueInfo: {
                                        id: 118,
                                        ground: "County Ground",
                                        city: "Chelmsford",
                                        timezone: "+01:00",
                                        latitude: "51.731580",
                                        longitude: "0.469004",
                                    },
                                    currBatTeamId: 153,
                                    seriesStartDt: "1743724800000",
                                    seriesEndDt: "1759104000000",
                                    isTimeAnnounced: true,
                                    stateTitle: "Stumps",
                                },
                                matchScore: {
                                    team1Score: {
                                        inngs1: {
                                            inningsId: 1,
                                            runs: 296,
                                            wickets: 10,
                                            overs: 98.1,
                                        },
                                    },
                                    team2Score: {
                                        inngs1: {
                                            inningsId: 2,
                                            runs: 293,
                                            wickets: 4,
                                            overs: 90.6,
                                        },
                                    },
                                },
                            },
                            {
                                matchInfo: {
                                    matchId: 113085,
                                    seriesId: 9360,
                                    seriesName: "County Championship Division One 2025",
                                    matchDesc: "40th Match",
                                    matchFormat: "TEST",
                                    startDate: "1750586400000",
                                    endDate: "1750870800000",
                                    state: "Stumps",
                                    status: "Day 2: Stumps - Yorkshire trail by 333 runs",
                                    team1: {
                                        teamId: 139,
                                        teamName: "Nottinghamshire",
                                        teamSName: "NOTTS",
                                        imageId: 172206,
                                    },
                                    team2: {
                                        teamId: 146,
                                        teamName: "Yorkshire",
                                        teamSName: "YORKS",
                                        imageId: 172213,
                                    },
                                    venueInfo: {
                                        id: 18,
                                        ground: "Trent Bridge",
                                        city: "Nottingham",
                                        timezone: "+01:00",
                                        latitude: "52.936884",
                                        longitude: "-1.132230",
                                    },
                                    currBatTeamId: 146,
                                    seriesStartDt: "1743724800000",
                                    seriesEndDt: "1759104000000",
                                    isTimeAnnounced: true,
                                    stateTitle: "Stumps",
                                },
                                matchScore: {
                                    team1Score: {
                                        inngs1: {
                                            inningsId: 1,
                                            runs: 487,
                                            wickets: 10,
                                            overs: 132.4,
                                        },
                                    },
                                    team2Score: {
                                        inngs1: {
                                            inningsId: 2,
                                            runs: 154,
                                            wickets: 3,
                                            overs: 54.6,
                                        },
                                    },
                                },
                            },
                            {
                                matchInfo: {
                                    matchId: 113073,
                                    seriesId: 9360,
                                    seriesName: "County Championship Division One 2025",
                                    matchDesc: "38th Match",
                                    matchFormat: "TEST",
                                    startDate: "1750586400000",
                                    endDate: "1750870800000",
                                    state: "Stumps",
                                    status: "Day 2: Stumps - Warwickshire trail by 340 runs",
                                    team1: {
                                        teamId: 119,
                                        teamName: "Somerset",
                                        teamSName: "SOM",
                                        imageId: 172199,
                                    },
                                    team2: {
                                        teamId: 140,
                                        teamName: "Warwickshire",
                                        teamSName: "WARKS",
                                        imageId: 172207,
                                    },
                                    venueInfo: {
                                        id: 20,
                                        ground: "Edgbaston",
                                        city: "Birmingham",
                                        timezone: "+01:00",
                                        latitude: "52.455774",
                                        longitude: "-1.902624",
                                    },
                                    currBatTeamId: 140,
                                    seriesStartDt: "1743724800000",
                                    seriesEndDt: "1759104000000",
                                    isTimeAnnounced: true,
                                    stateTitle: "Stumps",
                                },
                                matchScore: {
                                    team1Score: {
                                        inngs1: {
                                            inningsId: 1,
                                            runs: 498,
                                            wickets: 10,
                                            overs: 133.3,
                                        },
                                    },
                                    team2Score: {
                                        inngs1: {
                                            inningsId: 2,
                                            runs: 158,
                                            wickets: 1,
                                            overs: 52.6,
                                        },
                                    },
                                },
                            },
                        ],
                    },
                },
                {
                    ad: {
                        name: "native_matches",
                        layout: "native_large",
                        position: 3,
                    },
                },
                {
                    seriesAdWrapper: {
                        seriesId: 9369,
                        seriesName: "County Championship Division Two 2025",
                        matches: [
                            {
                                matchInfo: {
                                    matchId: 113505,
                                    seriesId: 9369,
                                    seriesName: "County Championship Division Two 2025",
                                    matchDesc: "32nd Match",
                                    matchFormat: "TEST",
                                    startDate: "1750586400000",
                                    endDate: "1750870800000",
                                    state: "Stumps",
                                    status: "Day 2: Stumps - Lancashire trail by 254 runs",
                                    team1: {
                                        teamId: 150,
                                        teamName: "Kent",
                                        teamSName: "KENT",
                                        imageId: 172217,
                                    },
                                    team2: {
                                        teamId: 143,
                                        teamName: "Lancashire",
                                        teamSName: "LANCS",
                                        imageId: 172210,
                                    },
                                    venueInfo: {
                                        id: 408,
                                        ground: "Stanley Park",
                                        city: "Blackpool",
                                        timezone: "+01:00",
                                        latitude: "53.815945",
                                        longitude: "-3.030751",
                                    },
                                    currBatTeamId: 143,
                                    seriesStartDt: "1743724800000",
                                    seriesEndDt: "1759104000000",
                                    isTimeAnnounced: true,
                                    stateTitle: "Stumps",
                                },
                                matchScore: {
                                    team1Score: {
                                        inngs1: {
                                            inningsId: 1,
                                            runs: 374,
                                            wickets: 10,
                                            overs: 123.2,
                                        },
                                    },
                                    team2Score: {
                                        inngs1: {
                                            inningsId: 2,
                                            runs: 120,
                                            wickets: 1,
                                            overs: 37.6,
                                        },
                                    },
                                },
                            },
                            {
                                matchInfo: {
                                    matchId: 113496,
                                    seriesId: 9369,
                                    seriesName: "County Championship Division Two 2025",
                                    matchDesc: "30th Match",
                                    matchFormat: "TEST",
                                    startDate: "1750586400000",
                                    endDate: "1750870800000",
                                    state: "Stumps",
                                    status: "Day 2: Stumps - Leicestershire lead by 36 runs",
                                    team1: {
                                        teamId: 149,
                                        teamName: "Glamorgan",
                                        teamSName: "GLAM",
                                        imageId: 172216,
                                    },
                                    team2: {
                                        teamId: 145,
                                        teamName: "Leicestershire",
                                        teamSName: "LEIC",
                                        imageId: 172212,
                                    },
                                    venueInfo: {
                                        id: 222,
                                        ground: "Grace Road",
                                        city: "Leicester",
                                        timezone: "+01:00",
                                        latitude: "52.607861",
                                        longitude: "-1.142709",
                                    },
                                    currBatTeamId: 145,
                                    seriesStartDt: "1743724800000",
                                    seriesEndDt: "1759104000000",
                                    isTimeAnnounced: true,
                                    stateTitle: "Stumps",
                                },
                                matchScore: {
                                    team1Score: {
                                        inngs1: {
                                            inningsId: 1,
                                            runs: 353,
                                            wickets: 10,
                                            overs: 110.2,
                                        },
                                    },
                                    team2Score: {
                                        inngs1: {
                                            inningsId: 2,
                                            runs: 389,
                                            wickets: 3,
                                            overs: 78.6,
                                        },
                                    },
                                },
                            },
                            {
                                matchInfo: {
                                    matchId: 113499,
                                    seriesId: 9369,
                                    seriesName: "County Championship Division Two 2025",
                                    matchDesc: "31st Match",
                                    matchFormat: "TEST",
                                    startDate: "1750586400000",
                                    endDate: "1750870800000",
                                    state: "Stumps",
                                    status: "Day 2: Stumps - Gloucestershire trail by 149 runs",
                                    team1: {
                                        teamId: 151,
                                        teamName: "Gloucestershire",
                                        teamSName: "GLOUCS",
                                        imageId: 172218,
                                    },
                                    team2: {
                                        teamId: 144,
                                        teamName: "Derbyshire",
                                        teamSName: "DERBY",
                                        imageId: 172211,
                                    },
                                    venueInfo: {
                                        id: 63,
                                        ground: "County Ground",
                                        city: "Bristol",
                                        timezone: "+01:00",
                                        latitude: "51.477246",
                                        longitude: "-2.584212",
                                    },
                                    currBatTeamId: 151,
                                    seriesStartDt: "1743724800000",
                                    seriesEndDt: "1759104000000",
                                    isTimeAnnounced: true,
                                    stateTitle: "Stumps",
                                },
                                matchScore: {
                                    team1Score: {
                                        inngs1: {
                                            inningsId: 1,
                                            runs: 187,
                                            wickets: 10,
                                            overs: 59.2,
                                        },
                                        inngs2: {
                                            inningsId: 3,
                                            runs: 62,
                                            wickets: 1,
                                            overs: 21.6,
                                        },
                                    },
                                    team2Score: {
                                        inngs1: {
                                            inningsId: 2,
                                            runs: 398,
                                            wickets: 10,
                                            overs: 105.5,
                                        },
                                    },
                                },
                            },
                            {
                                matchInfo: {
                                    matchId: 113490,
                                    seriesId: 9369,
                                    seriesName: "County Championship Division Two 2025",
                                    matchDesc: "29th Match",
                                    matchFormat: "TEST",
                                    startDate: "1750586400000",
                                    endDate: "1750870800000",
                                    state: "Stumps",
                                    status: "Day 2: Stumps - Northamptonshire trail by 105 runs",
                                    team1: {
                                        teamId: 74,
                                        teamName: "Middlesex",
                                        teamSName: "MDX",
                                        imageId: 172170,
                                    },
                                    team2: {
                                        teamId: 142,
                                        teamName: "Northamptonshire",
                                        teamSName: "NHNTS",
                                        imageId: 172209,
                                    },
                                    venueInfo: {
                                        id: 119,
                                        ground: "County Ground",
                                        city: "Northampton",
                                        timezone: "+01:00",
                                        latitude: "52.248160",
                                        longitude: "-0.871060",
                                    },
                                    currBatTeamId: 142,
                                    seriesStartDt: "1743724800000",
                                    seriesEndDt: "1759104000000",
                                    isTimeAnnounced: true,
                                    stateTitle: "Stumps",
                                },
                                matchScore: {
                                    team1Score: {
                                        inngs1: {
                                            inningsId: 1,
                                            runs: 413,
                                            wickets: 10,
                                            overs: 100.6,
                                        },
                                    },
                                    team2Score: {
                                        inngs1: {
                                            inningsId: 2,
                                            runs: 308,
                                            wickets: 5,
                                            overs: 88.6,
                                        },
                                    },
                                },
                            },
                        ],
                    },
                },
            ],
        },
    ],
    filters: {
        matchType: ["International", "League", "Domestic", "Women"],
    },
    appIndex: {
        seoTitle: "Live Cricket Score - Scorecard and Match Results",
        webURL: "www.cricbuzz.com/live-cricket-scores/",
    },
    responseLastUpdated: "1750756564",
};
